definitions:
  batch.CreateBatchInputDto:
    properties:
      name:
        type: string
      recipe_id:
        type: string
      start_date:
        type: string
    type: object
  batch.CreateBatchStepInputDto:
    properties:
      batch_id:
        type: string
      recipe_step_id:
        type: string
      started_at:
        type: string
      user_id:
        type: string
    type: object
  brewery.CreateBreweryInputDto:
    properties:
      email:
        type: string
      name:
        type: string
      user_id:
        type: string
    type: object
  brewery.GetUserBreweriesOutputDTO:
    properties:
      email:
        type: string
      error_message:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
      statusCode:
        type: integer
    type: object
  brewery.InviteUserInputDTO:
    properties:
      brewery_id:
        type: string
      invited_user_id:
        type: string
      inviting_user_id:
        type: string
      role:
        type: string
    type: object
  brewery.InviteUserOutputDTO:
    properties:
      brewery_id:
        type: string
      error_message:
        type: string
      invited_user_id:
        type: string
      inviting_user_id:
        type: string
      role:
        type: string
      statusCode:
        type: integer
    type: object
  common.HttpErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
  recipe.CreateRecipeInputDto:
    properties:
      brewery_id:
        type: string
      name:
        type: string
      steps:
        items:
          $ref: '#/definitions/recipe.Steps'
        type: array
    type: object
  recipe.Steps:
    properties:
      instruction:
        type: string
      name:
        type: string
    type: object
  user.CreateUserInputDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  user.LoginUserInputDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.LoginUserOutputDto:
    properties:
      email:
        type: string
      error_message:
        type: string
      statusCode:
        type: integer
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.LoginUserInputDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginUserOutputDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Login user
      tags:
      - user
  /batch:
    post:
      consumes:
      - application/json
      description: Create batch
      parameters:
      - description: batch
        in: body
        name: batch
        required: true
        schema:
          $ref: '#/definitions/batch.CreateBatchInputDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/batch.CreateBatchInputDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Create batch
      tags:
      - batch
  /brewery:
    get:
      consumes:
      - application/json
      description: Get brewery by user id
      parameters:
      - description: User id
        in: path
        name: brewery
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/brewery.GetUserBreweriesOutputDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Get brewery by user id
      tags:
      - brewery
    post:
      consumes:
      - application/json
      description: Create brewery
      parameters:
      - description: brewery
        in: body
        name: brewery
        required: true
        schema:
          $ref: '#/definitions/brewery.CreateBreweryInputDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/brewery.CreateBreweryInputDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Create brewery
      tags:
      - brewery
  /brewery/invite:
    post:
      consumes:
      - application/json
      description: Invite user to a brewery
      parameters:
      - description: invite
        in: body
        name: invite
        required: true
        schema:
          $ref: '#/definitions/brewery.InviteUserInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/brewery.InviteUserOutputDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Invite user
      tags:
      - brewery
  /recipes:
    post:
      consumes:
      - application/json
      description: Create recipe
      parameters:
      - description: recipe
        in: body
        name: recipe
        required: true
        schema:
          $ref: '#/definitions/recipe.CreateRecipeInputDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/recipe.CreateRecipeInputDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Create recipe
      tags:
      - recipe
  /start-batch:
    post:
      consumes:
      - application/json
      description: Create batch step
      parameters:
      - description: batch step
        in: body
        name: batch
        required: true
        schema:
          $ref: '#/definitions/batch.CreateBatchStepInputDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/batch.CreateBatchStepInputDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Create batch step
      tags:
      - batch
  /users:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserInputDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateUserInputDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HttpErrorResponse'
      summary: Create user
      tags:
      - user
swagger: "2.0"
